version: 0.1

projects:
  # Development environment cost estimation
  - path: terraform
    name: octonius-dev
    terraform_plan_flags: -var-file=config/dev.tfvars
    usage_file: infracost-usage-dev.yml
    
  # Staging environment cost estimation  
  - path: terraform
    name: octonius-staging
    terraform_plan_flags: -var-file=config/staging.tfvars
    usage_file: infracost-usage-staging.yml
    
  # Production environment cost estimation
  - path: terraform
    name: octonius-prod
    terraform_plan_flags: -var-file=config/prod.tfvars
    usage_file: infracost-usage-prod.yml

# Currency and formatting options
currency: USD
format: table

# Cost thresholds for alerts
cost_threshold:
  percentage_threshold: 20  # Alert if cost increases by more than 20%
  absolute_threshold: 100   # Alert if cost increases by more than $100/month

# Default usage estimates (can be overridden per environment)
usage:
  # EC2 instances
  aws_instance:
    operating_system: linux
    reserved_instance_type: ""
    reserved_instance_term: ""
    reserved_instance_payment_option: ""
    
  # NAT Gateway
  aws_nat_gateway:
    monthly_data_processed_gb: 100  # Estimate 100GB per month
    
  # Application Load Balancer
  aws_lb:
    monthly_data_processed_gb: 100
    
  # RDS
  aws_db_instance:
    backup_storage_gb: 100
    
  # S3
  aws_s3_bucket:
    standard:
      storage_gb: 50
      monthly_tier_1_requests: 10000
      monthly_tier_2_requests: 1000
      monthly_select_data_scanned_gb: 0
      monthly_select_data_returned_gb: 0
    intelligent_tiering:
      frequent_access_storage_gb: 0
      infrequent_access_storage_gb: 0
      archive_instant_access_storage_gb: 0
      archive_access_storage_gb: 0
      deep_archive_storage_gb: 0
      early_delete_gb: 0
      monitoring_automation_monthly_objects: 0
    glacier_flexible_retrieval:
      storage_gb: 0
      monthly_retrieval_gb: 0
      monthly_data_returned_gb: 0
      early_delete_gb: 0
      
  # CloudWatch
  aws_cloudwatch_log_group:
    monthly_data_ingested_gb: 10
    monthly_data_storage_gb: 10
    monthly_data_scanned_gb: 0
    
  # VPC Flow Logs
  aws_flow_log:
    monthly_gb: 5 