# Dynamic Terraform Locals - Generated by scripts/generate-terraform-config.sh
# This file is automatically generated based on branch/environment detection

locals {
  # Environment and project info
  environment  = var.environment
  project_name = var.project_name
  aws_region   = var.aws_region
  account_id   = data.aws_caller_identity.current.account_id
  
  # Computed names and identifiers
  name_prefix = "${local.environment}-${local.project_name}"
  
  # Resource naming
  vpc_name = "${local.name_prefix}-vpc"
  
  # Backend resources (for reference)
  state_bucket         = "${local.environment}-${local.project_name}-terraform-state-${local.aws_region}"
  state_dynamodb_table = "${local.environment}-${local.project_name}-terraform-locks-${local.aws_region}"
  
  # Common tags applied to all resources
  common_tags = {
    Environment = local.environment
    Project     = local.project_name
    ManagedBy   = "terraform"
    Repository  = "octonius-platform"
    Branch      = local.environment # Since env is derived from branch
    Account     = local.account_id
    Region      = local.aws_region
  }
  
  # Environment-specific configurations
  is_production = local.environment == "prod"
  is_development = local.environment == "dev"
  is_feature_branch = !local.is_production && !local.is_development
} 