# Dynamic Terraform Locals - Generated by scripts/generate-terraform-config.sh
# This file is automatically generated based on branch/environment detection

locals {
  # Environment and project info
  environment  = var.environment || "dev"
  project_name = var.project_name
  aws_region   = var.aws_region
  account_id   = var.account_id

  # Default whitelisted IPs
  default_whitelisted_ips = [
    "10.0.0.0/8",       # Private network
    "172.16.0.0/12",    # Private network
    "192.168.0.0/16",   # Private network
    "183.83.0.0/32" # Shubham's IP
  ]
  
  # Combine default IPs with any additional IPs provided
  all_whitelisted_ips = distinct(concat(local.default_whitelisted_ips, var.whitelisted_ips))

  # Computed names and identifiers
  name_prefix = "${local.environment}-${local.project_name}"

  # Resource naming
  vpc_name = "${local.name_prefix}-vpc"

  # Backend resources (for reference)
  state_bucket         = "${local.environment}-${local.project_name}-terraform-state-${local.aws_region}"
  state_dynamodb_table = "${local.environment}-${local.project_name}-terraform-locks-${local.aws_region}"

  # Common tags applied to all resources
  common_tags = {
    Environment = local.environment
    Project     = local.project_name
    ManagedBy   = "terraform"
    Repository  = "octonius-platform"
    Branch      = local.environment
    Account     = local.account_id
    Region      = local.aws_region

    # Cost allocation tags
    CostCenter     = local.is_production ? "PROD-OCTONIUS" : "DEV-OCTONIUS"
    BusinessUnit   = "Engineering"
    BudgetCategory = local.is_production ? "Production" : "Development"

    # Backup and compliance tags
    BackupPolicy    = local.is_production ? "Daily" : "Weekly"
    DataSensitivity = "Confidential"

    # Technical tags
    AutoShutdown      = local.is_production ? "false" : "true"
    MaintenanceWindow = local.is_production ? "sat:22:00-sun:02:00" : "sun:02:00-sun:06:00"
  }

  # Environment-specific configurations
  is_production     = local.environment == "prod"
  is_development    = local.environment == "dev"
  is_feature_branch = !local.is_production && !local.is_development

  # Resource sizing and limits
  rds_instance_class = {
    prod = "db.t4g.medium"
    dev  = "db.t4g.micro"
  }

  redis_node_type = {
    prod = "cache.t4g.medium"
    dev  = "cache.t4g.micro"
  }
} 